name: smart_feeder_desktop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  accordion: ^2.6.0
  carousel_slider: ^5.1.1
  delightful_toast: ^1.1.0
  dotted_border: ^3.1.0
  excel: ^4.0.6
  file_picker: ^10.2.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_libserialport: ^0.5.0
  get: ^4.7.2
  get_storage: ^2.1.1
  http: ^1.5.0
  image_picker: ^1.2.0
  input_quantity: ^2.5.1
  intl: ^0.20.2
  lottie: ^3.3.0
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.5
  mqtt_client: ^10.10.0
  pdf: ^3.11.3
  printing: ^5.14.2
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  syncfusion_flutter_datagrid: ^30.1.40
  toastification: ^3.0.3
  top_snackbar_flutter: ^3.3.0
  uuid: ^4.5.1
  window_manager: ^0.5.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/horse_walker/
    - assets/images/water_tank/
    - assets/images/feed_tank/
    - assets/images/stable_water/
    - assets/images/stable_feed/
    - assets/lottie/