import 'package:get/get.dart';
import 'package:smart_feeder_desktop/app/models/halter_device_model.dart';
import 'package:smart_feeder_desktop/app/models/horse_model.dart';
import 'package:smart_feeder_desktop/app/models/stable_model.dart';

class HalterDashboardController extends GetxController {
  RxInt selectedStableIndex = 0.obs;
  StableModel get selectedStable => stableList[selectedStableIndex.value];

  final RxList<HorseModel> horseList = <HorseModel>[
    HorseModel(
      horseId: 'Kuda 001',
      name: 'Thunder',
      gender: 'Jantan',
      type: 'Lokal',
      dateOfBirth: DateTime(2023, 1, 1),
      dateJoinedStable: DateTime(2024, 2, 2),
      healthStatus: 'Sehat',
      imageAsset: 'assets/images/horse1.png',
    ),
    HorseModel(
      horseId: 'Kuda 002',
      name: 'Bella',
      gender: 'Betina',
      type: 'Lokal',
      dateOfBirth: DateTime(2022, 6, 10),
      dateJoinedStable: DateTime(2024, 3, 5),
      healthStatus: 'Sehat',
      imageAsset: 'assets/images/horse2.png',
    ),
    HorseModel(
      horseId: 'Kuda 003',
      name: 'Spirit',
      gender: 'Jantan',
      type: 'Arabian',
      dateOfBirth: DateTime(2021, 4, 15),
      dateJoinedStable: DateTime(2024, 1, 27),
      healthStatus: 'Sakit',
      imageAsset: 'assets/images/horse3.png',
    ),
    HorseModel(
      horseId: 'Kuda 004',
      name: 'Daisy',
      gender: 'Betina',
      type: 'Lokal',
      dateOfBirth: DateTime(2022, 8, 21),
      dateJoinedStable: DateTime(2024, 4, 11),
      healthStatus: 'Sehat',
      imageAsset: 'assets/images/horse4.png',
    ),
    HorseModel(
      horseId: 'Kuda 005',
      name: 'Storm',
      gender: 'Jantan',
      type: 'Quarter',
      dateOfBirth: DateTime(2020, 12, 3),
      dateJoinedStable: DateTime(2024, 2, 15),
      healthStatus: 'Sehat',
      imageAsset: 'assets/images/horse5.png',
    ),
    HorseModel(
      horseId: 'Kuda 006',
      name: 'Molly',
      gender: 'Betina',
      type: 'Lokal',
      dateOfBirth: DateTime(2021, 11, 8),
      dateJoinedStable: DateTime(2024, 5, 1),
      healthStatus: 'Sehat',
      imageAsset: 'assets/images/horse6.png',
    ),
    HorseModel(
      horseId: 'Kuda 007',
      name: 'Rocky',
      gender: 'Jantan',
      type: 'Lokal',
      dateOfBirth: DateTime(2020, 7, 19),
      dateJoinedStable: DateTime(2024, 5, 6),
      healthStatus: 'Sakit',
      imageAsset: 'assets/images/horse7.png',
    ),
    HorseModel(
      horseId: 'Kuda 008',
      name: 'Luna',
      gender: 'Betina',
      type: 'Lokal',
      dateOfBirth: DateTime(2022, 9, 14),
      dateJoinedStable: DateTime(2024, 6, 2),
      healthStatus: 'Sehat',
      imageAsset: 'assets/images/horse8.png',
    ),
    HorseModel(
      horseId: 'Kuda 009',
      name: 'Shadow',
      gender: 'Jantan',
      type: 'Lokal',
      dateOfBirth: DateTime(2023, 3, 8),
      dateJoinedStable: DateTime(2024, 6, 10),
      healthStatus: 'Sehat',
      imageAsset: 'assets/images/horse9.png',
    ),
    HorseModel(
      horseId: 'Kuda 010',
      name: 'Rose',
      gender: 'Betina',
      type: 'Lokal',
      dateOfBirth: DateTime(2021, 5, 30),
      dateJoinedStable: DateTime(2024, 7, 1),
      healthStatus: 'Sehat',
      imageAsset: 'assets/images/horse10.png',
    ),
    HorseModel(
      horseId: 'Kuda 011',
      name: 'Jack',
      gender: 'Jantan',
      type: 'Lokal',
      dateOfBirth: DateTime(2020, 10, 12),
      dateJoinedStable: DateTime(2024, 7, 6),
      healthStatus: 'Sehat',
      imageAsset: 'assets/images/horse11.png',
    ),
    HorseModel(
      horseId: 'Kuda 012',
      name: 'Lily',
      gender: 'Betina',
      type: 'Lokal',
      dateOfBirth: DateTime(2022, 2, 18),
      dateJoinedStable: DateTime(2024, 7, 14),
      healthStatus: 'Sakit',
      imageAsset: 'assets/images/horse12.png',
    ),
    HorseModel(
      horseId: 'Kuda 013',
      name: 'Max',
      gender: 'Jantan',
      type: 'Lokal',
      dateOfBirth: DateTime(2021, 8, 2),
      dateJoinedStable: DateTime(2024, 7, 18),
      healthStatus: 'Sehat',
      imageAsset: 'assets/images/horse13.png',
    ),
    HorseModel(
      horseId: 'Kuda 014',
      name: 'Ruby',
      gender: 'Betina',
      type: 'Lokal',
      dateOfBirth: DateTime(2023, 4, 22),
      dateJoinedStable: DateTime(2024, 7, 20),
      healthStatus: 'Sehat',
      imageAsset: 'assets/images/horse14.png',
    ),
    HorseModel(
      horseId: 'Kuda 015',
      name: 'Leo',
      gender: 'Jantan',
      type: 'Lokal',
      dateOfBirth: DateTime(2020, 6, 9),
      dateJoinedStable: DateTime(2024, 7, 21),
      healthStatus: 'Sehat',
      imageAsset: 'assets/images/horse15.png',
    ),
    HorseModel(
      horseId: 'Kuda 016',
      name: 'Maya',
      gender: 'Betina',
      type: 'Lokal',
      dateOfBirth: DateTime(2021, 3, 17),
      dateJoinedStable: DateTime(2024, 7, 22),
      healthStatus: 'Sehat',
      imageAsset: 'assets/images/horse16.png',
    ),
  ].obs;

  // Data dummy stable/kandang (stableList), relasi 1 kuda per kandang lewat horseId
  final RxList<StableModel> stableList = <StableModel>[
    StableModel(
      stableName: 'Kandang 1',
      imageAsset: 'assets/images/stable.jpg',
      scheduleText: 'Penjadwalan',
      isActive: true,
      remainingWater: 4.2,
      remainingFeed: 38.0,
      lastFeedText: '2 jam yang lalu',
      horseId: 'Kuda 001',
    ),
    StableModel(
      stableName: 'Kandang 2',
      imageAsset: 'assets/images/stable.jpg',
      scheduleText: 'Otomatis',
      isActive: false,
      remainingWater: 1.5,
      remainingFeed: 12.0,
      lastFeedText: '1 jam yang lalu',
      horseId: 'Kuda 002',
    ),
    StableModel(
      stableName: 'Kandang 3',
      imageAsset: 'assets/images/stable.jpg',
      scheduleText: 'Manual',
      isActive: true,
      remainingWater: 0.8,
      remainingFeed: 5.5,
      lastFeedText: '30 menit yang lalu',
      horseId: 'Kuda 003',
    ),
    StableModel(
      stableName: 'Kandang 4',
      imageAsset: 'assets/images/stable.jpg',
      scheduleText: 'Otomatis',
      isActive: true,
      remainingWater: 5.0,
      remainingFeed: 49.0,
      lastFeedText: '10 menit yang lalu',
      horseId: 'Kuda 004',
    ),
    StableModel(
      stableName: 'Kandang 5',
      imageAsset: 'assets/images/stable.jpg',
      scheduleText: 'Manual',
      isActive: false,
      remainingWater: 0.2,
      remainingFeed: 0.0,
      lastFeedText: '3 jam yang lalu',
      horseId: 'Kuda 005',
    ),
    StableModel(
      stableName: 'Kandang 6',
      imageAsset: 'assets/images/stable.jpg',
      scheduleText: 'Penjadwalan',
      isActive: true,
      remainingWater: 3.8,
      remainingFeed: 30.0,
      lastFeedText: '2 jam yang lalu',
      horseId: 'Kuda 006',
    ),
    StableModel(
      stableName: 'Kandang 7',
      imageAsset: 'assets/images/stable.jpg',
      scheduleText: 'Otomatis',
      isActive: true,
      remainingWater: 4.0,
      remainingFeed: 25.0,
      lastFeedText: '1 jam yang lalu',
      horseId: 'Kuda 007',
    ),
    StableModel(
      stableName: 'Kandang 8',
      imageAsset: 'assets/images/stable.jpg',
      scheduleText: 'Manual',
      isActive: false,
      remainingWater: 2.9,
      remainingFeed: 12.5,
      lastFeedText: '2 jam yang lalu',
      horseId: 'Kuda 008',
    ),
    StableModel(
      stableName: 'Kandang 9',
      imageAsset: 'assets/images/stable.jpg',
      scheduleText: 'Otomatis',
      isActive: true,
      remainingWater: 4.7,
      remainingFeed: 41.0,
      lastFeedText: '15 menit yang lalu',
      horseId: 'Kuda 009',
    ),
    StableModel(
      stableName: 'Kandang 10',
      imageAsset: 'assets/images/stable.jpg',
      scheduleText: 'Manual',
      isActive: true,
      remainingWater: 1.6,
      remainingFeed: 8.0,
      lastFeedText: '5 jam yang lalu',
      horseId: 'Kuda 010',
    ),
    StableModel(
      stableName: 'Kandang 11',
      imageAsset: 'assets/images/stable.jpg',
      scheduleText: 'Penjadwalan',
      isActive: true,
      remainingWater: 3.0,
      remainingFeed: 28.0,
      lastFeedText: '40 menit yang lalu',
      horseId: 'Kuda 011',
    ),
    StableModel(
      stableName: 'Kandang 12',
      imageAsset: 'assets/images/stable.jpg',
      scheduleText: 'Otomatis',
      isActive: false,
      remainingWater: 0.5,
      remainingFeed: 3.0,
      lastFeedText: '6 jam yang lalu',
      horseId: 'Kuda 012',
    ),
    StableModel(
      stableName: 'Kandang 13',
      imageAsset: 'assets/images/stable.jpg',
      scheduleText: 'Manual',
      isActive: true,
      remainingWater: 2.1,
      remainingFeed: 20.0,
      lastFeedText: '1 jam yang lalu',
      horseId: 'Kuda 013',
    ),
    StableModel(
      stableName: 'Kandang 14',
      imageAsset: 'assets/images/stable.jpg',
      scheduleText: 'Otomatis',
      isActive: true,
      remainingWater: 4.9,
      remainingFeed: 45.0,
      lastFeedText: '12 menit yang lalu',
      horseId: 'Kuda 014',
    ),
    StableModel(
      stableName: 'Kandang 15',
      imageAsset: 'assets/images/stable.jpg',
      scheduleText: 'Manual',
      isActive: false,
      remainingWater: 0.3,
      remainingFeed: 2.0,
      lastFeedText: '8 jam yang lalu',
      horseId: 'Kuda 015',
    ),
    StableModel(
      stableName: 'Kandang 16',
      imageAsset: 'assets/images/stable.jpg',
      scheduleText: 'Otomatis',
      isActive: true,
      remainingWater: 5.0,
      remainingFeed: 50.0,
      lastFeedText: 'baru saja',
      horseId: 'Kuda 016',
    ),
  ].obs;

  final RxList<HalterDeviceModel> halterDeviceList = <HalterDeviceModel>[
    HalterDeviceModel(
      id: 'Halter 001',
      serialNumber: 'SN123456789',
      usedByHorse: 'Kuda 001',
      status: 'Aktif',
    ),
    HalterDeviceModel(
      id: 'Halter 002',
      serialNumber: 'SN987654321',
      usedByHorse: 'Kuda 002',
      status: 'Tidak Aktif',
    ),
    HalterDeviceModel(
      id: 'Halter 003',
      serialNumber: 'SN1122334455',
      usedByHorse: 'Kuda 003',
      status: 'Aktif',
    ),
    HalterDeviceModel(
      id: 'Halter 004',
      serialNumber: 'SN5566778899',
      usedByHorse: 'Kuda 004',
      status: 'Aktif',
    ),
    HalterDeviceModel(
      id: 'Halter 005',
      serialNumber: 'SN9988776655',
      usedByHorse: 'Kuda 005',
      status: 'Aktif',
    ),
    HalterDeviceModel(
      id: 'Halter 006',
      serialNumber: 'SN2233445566',
      usedByHorse: 'Kuda 006',
      status: 'Tidak Aktif',
    ),
    HalterDeviceModel(
      id: 'Halter 007',
      serialNumber: 'SN3344556677',
      usedByHorse: 'Kuda 007',
      status: 'Aktif',
    ),
    HalterDeviceModel(
      id: 'Halter 008',
      serialNumber: 'SN4455667788',
      usedByHorse: 'Kuda 008',
      status: 'Aktif',
    ),
    HalterDeviceModel(
      id: 'Halter 009',
      serialNumber: 'SN5566778890',
      usedByHorse: 'Kuda 009',
      status: 'Tidak Aktif',
    ),
    HalterDeviceModel(
      id: 'Halter 010',
      serialNumber: 'SN6677889900',
      usedByHorse: 'Kuda 010',
      status: 'Aktif',
    ),
    HalterDeviceModel(
      id: 'Halter 011',
      serialNumber: 'SN7788990011',
      usedByHorse: 'Kuda 011',
      status: 'Aktif',
    ),
    HalterDeviceModel(
      id: 'Halter 012',
      serialNumber: 'SN8899001122',
      usedByHorse: 'Kuda 012',
      status: 'Tidak Aktif',
    ),
    HalterDeviceModel(
      id: 'Halter 013',
      serialNumber: 'SN9900112233',
      usedByHorse: 'Kuda 013',
      status: 'Aktif',
    ),
    HalterDeviceModel(
      id: 'Halter 014',
      serialNumber: 'SN1011121314',
      usedByHorse: 'Kuda 014',
      status: 'Aktif',
    ),
    HalterDeviceModel(
      id: 'Halter 015',
      serialNumber: 'SN1213141516',
      usedByHorse: 'Kuda 015',
      status: 'Tidak Aktif',
    ),
    HalterDeviceModel(
      id: 'Halter 016',
      serialNumber: 'SN1415161718',
      usedByHorse: 'Kuda 016',
      status: 'Aktif',
    ),
  ].obs;

  HorseModel getHorseById(String horseId) {
    return horseList.firstWhere((horse) => horse.horseId == horseId);
  }
  
}
