import 'package:get/get.dart';
import 'package:smart_feeder_desktop/app/models/horse_model.dart';

class HalterHorseController extends GetxController {
  final RxList<HorseModel> horseList = <HorseModel>[
    // Stable 1
    HorseModel(
      horseId: 'H1',
      name: 'Farel',
      type: 'local',
      gender: 'male',
      age: '1,47 tahun',
      roomId: 'R1',
    ),
    HorseModel(
      horseId: 'H2',
      name: 'Bella',
      type: 'crossbred',
      gender: 'female',
      age: '2,15 tahun',
      roomId: 'R2',
    ),
    HorseModel(
      horseId: 'H3',
      name: 'Jupiter',
      type: 'local',
      gender: 'male',
      age: '3,05 tahun',
      roomId: 'R3',
    ),
    HorseModel(
      horseId: 'H4',
      name: 'Mawar',
      type: 'crossbred',
      gender: 'female',
      age: '1,98 tahun',
      roomId: 'R4',
    ),
    HorseModel(
      horseId: 'H5',
      name: 'Tornado',
      type: 'local',
      gender: 'male',
      age: '2,80 tahun',
      roomId: 'R5',
    ),
    HorseModel(
      horseId: 'H6',
      name: 'Dewi',
      type: 'crossbred',
      gender: 'female',
      age: '2,60 tahun',
      roomId: 'R6',
    ),
    // Stable 2
    HorseModel(
      horseId: 'H7',
      name: 'Raja',
      type: 'local',
      gender: 'male',
      age: '3,40 tahun',
      roomId: 'R7',
    ),
    HorseModel(
      horseId: 'H8',
      name: 'Putri',
      type: 'crossbred',
      gender: 'female',
      age: '1,80 tahun',
      roomId: 'R8',
    ),
    HorseModel(
      horseId: 'H9',
      name: 'Guntur',
      type: 'local',
      gender: 'male',
      age: '2,50 tahun',
      roomId: 'R9',
    ),
    HorseModel(
      horseId: 'H10',
      name: 'Bunga',
      type: 'crossbred',
      gender: 'female',
      age: '2,10 tahun',
      roomId: 'R10',
    ),
    HorseModel(
      horseId: 'H11',
      name: 'Bintang',
      type: 'local',
      gender: 'male',
      age: '4,00 tahun',
      roomId: 'R11',
    ),
    HorseModel(
      horseId: 'H12',
      name: 'Melati',
      type: 'crossbred',
      gender: 'female',
      age: '3,20 tahun',
      roomId: 'R12',
    ),
    // Stable 3
    HorseModel(
      horseId: 'H13',
      name: 'Satria',
      type: 'local',
      gender: 'male',
      age: '2,70 tahun',
      roomId: 'R13',
    ),
    HorseModel(
      horseId: 'H14',
      name: 'Citra',
      type: 'crossbred',
      gender: 'female',
      age: '1,60 tahun',
      roomId: 'R14',
    ),
    HorseModel(
      horseId: 'H15',
      name: 'Mega',
      type: 'local',
      gender: 'male',
      age: '3,90 tahun',
      roomId: 'R15',
    ),
    HorseModel(
      horseId: 'H16',
      name: 'Embun',
      type: 'crossbred',
      gender: 'female',
      age: '2,00 tahun',
      roomId: 'R16',
    ),
    HorseModel(
      horseId: 'H17',
      name: 'Petir',
      type: 'local',
      gender: 'male',
      age: '2,30 tahun',
      roomId: 'R17',
    ),
    HorseModel(
      horseId: 'H18',
      name: 'Indah',
      type: 'crossbred',
      gender: 'female',
      age: '2,45 tahun',
      roomId: 'R18',
    ),
  ].obs;

}