import 'package:get/get.dart';
import 'package:smart_feeder_desktop/app/models/feed_model.dart';

class FeedController extends GetxController {
  final RxList<FeedModel> feedStocks = <FeedModel>[
    FeedModel(
      id: 'FS001',
      feedName: 'Pakan Kuda Premium',
      quantity: 120,
      dateIn: DateTime(2025, 7, 15, 8, 45),
      status: 'Masuk',
    ),
    FeedModel(
      id: 'FS002',
      feedName: 'Pakan Kuda Premium',
      quantity: 80,
      dateIn: DateTime(2025, 7, 16, 10, 30),
      status: 'Masuk',
    ),
    FeedModel(
      id: 'FS003',
      feedName: 'Pakan Kuda Premium',
      quantity: 60,
      dateIn: DateTime(2025, 7, 17, 12, 00),
      status: 'Keluar',
    ),
    FeedModel(
      id: 'FS004',
      feedName: 'Pakan Kuda Premium',
      quantity: 150,
      dateIn: DateTime(2025, 7, 18, 9, 20),
      status: 'Masuk',
    ),
    FeedModel(
      id: 'FS005',
      feedName: 'Pakan Kuda Premium',
      quantity: 40,
      dateIn: DateTime(2025, 7, 18, 16, 45),
      status: 'Rusak',
    ),
    FeedModel(
      id: 'FS006',
      feedName: 'Pakan Kuda Premium',
      quantity: 200,
      dateIn: DateTime(2025, 7, 19, 7, 10),
      status: 'Masuk',
    ),
    FeedModel(
      id: 'FS007',
      feedName: 'Pakan Kuda Premium',
      quantity: 90,
      dateIn: DateTime(2025, 7, 19, 18, 30),
      status: 'Keluar',
    ),
    FeedModel(
      id: 'FS008',
      feedName: 'Pakan Kuda Premium',
      quantity: 110,
      dateIn: DateTime(2025, 7, 20, 11, 15),
      status: 'Masuk',
    ),
    FeedModel(
      id: 'FS009',
      feedName: 'Pakan Kuda Premium',
      quantity: 30,
      dateIn: DateTime(2025, 7, 20, 13, 55),
      status: 'Rusak',
    ),
    FeedModel(
      id: 'FS010',
      feedName: 'Pakan Kuda Premium',
      quantity: 130,
      dateIn: DateTime(2025, 7, 21, 9, 25),
      status: 'Masuk',
    ),
    FeedModel(
      id: 'FS011',
      feedName: 'Pakan Kuda Premium',
      quantity: 75,
      dateIn: DateTime(2025, 7, 21, 15, 00),
      status: 'Keluar',
    ),
    FeedModel(
      id: 'FS012',
      feedName: 'Pakan Kuda Premium',
      quantity: 95,
      dateIn: DateTime(2025, 7, 22, 8, 30),
      status: 'Masuk',
    ),
    FeedModel(
      id: 'FS013',
      feedName: 'Pakan Kuda Premium',
      quantity: 50,
      dateIn: DateTime(2025, 7, 22, 14, 10),
      status: 'Rusak',
    ),
    FeedModel(
      id: 'FS014',
      feedName: 'Pakan Kuda Premium',
      quantity: 160,
      dateIn: DateTime(2025, 7, 23, 10, 45),
      status: 'Masuk',
    ),
    FeedModel(
      id: 'FS015',
      feedName: 'Pakan Kuda Premium',
      quantity: 85,
      dateIn: DateTime(2025, 7, 23, 17, 20),
      status: 'Keluar',
    ),
    FeedModel(
      id: 'FS016',
      feedName: 'Pakan Kuda Premium',
      quantity: 140,
      dateIn: DateTime(2025, 7, 24, 9, 50),
      status: 'Masuk',
    ),
    FeedModel(
      id: 'FS017',
      feedName: 'Pakan Kuda Premium',
      quantity: 55,
      dateIn: DateTime(2025, 7, 24, 15, 30),
      status: 'Rusak',
    ),
    FeedModel(
      id: 'FS018',
      feedName: 'Pakan Kuda Premium',
      quantity: 170,
      dateIn: DateTime(2025, 7, 25, 8, 10),
      status: 'Masuk',
    ),
    FeedModel(
      id: 'FS019',
      feedName: 'Pakan Kuda Premium',
      quantity: 70,
      dateIn: DateTime(2025, 7, 25, 13, 25),
      status: 'Keluar',
    ),
    FeedModel(
      id: 'FS020',
      feedName: 'Pakan Kuda Premium',
      quantity: 100,
      dateIn: DateTime(2025, 7, 25, 18, 40),
      status: 'Masuk',
    ),
  ].obs;
}
