import 'package:get/get.dart';
import 'package:smart_feeder_desktop/app/models/cctv_model.dart';
import 'package:smart_feeder_desktop/app/models/room_model.dart';

class HalterRoomController extends GetxController {

  final RxList<RoomModel> roomList = <RoomModel>[
    // Stable 1
    RoomModel(
      roomId: 'R1',
      name: 'Ruangan 1',
      deviceSerial: 'SRIPB1223001',
      status: 'used',
      cctvIds: ['CCTV1', 'CCTV2'],
      stableId: 'S1',
      horseId: 'H1',
      remainingWater: 43.0,
      remainingFeed: 30.0,
      scheduleType: 'penjadwalan',
    ),
    RoomModel(
      roomId: 'R2',
      name: 'Ruangan 2',
      deviceSerial: 'SRIPB1223002',
      status: 'available',
      cctvIds: ['CCTV3', 'CCTV4'],
      stableId: 'S1',
      horseId: 'H2',
      remainingWater: 21.0,
      remainingFeed: 15.0,
      scheduleType: 'otomatis',
    ),
    RoomModel(
      roomId: 'R3',
      name: 'Ruangan 3',
      deviceSerial: 'SRIPB1223003',
      status: 'used',
      cctvIds: ['CCTV5', 'CCTV6'],
      stableId: 'S1',
      horseId: 'H3',
      remainingWater: 11.0,
      remainingFeed: 12.0,
      scheduleType: 'manual',
    ),
    RoomModel(
      roomId: 'R4',
      name: 'Ruangan 4',
      deviceSerial: 'SRIPB1223004',
      status: 'available',
      cctvIds: ['CCTV7', 'CCTV8'],
      stableId: 'S1',
      horseId: 'H4',
      remainingWater: 50.0,
      remainingFeed: 17.0,
      scheduleType: 'penjadwalan',
    ),
    RoomModel(
      roomId: 'R5',
      name: 'Ruangan 5',
      deviceSerial: 'SRIPB1223005',
      status: 'used',
      cctvIds: ['CCTV9', 'CCTV10'],
      stableId: 'S1',
      horseId: 'H5',
      remainingWater: 18.0,
      remainingFeed: 21.0,
      scheduleType: 'otomatis',
    ),
    RoomModel(
      roomId: 'R6',
      name: 'Ruangan 6',
      deviceSerial: 'SRIPB1223006',
      status: 'available',
      cctvIds: ['CCTV11', 'CCTV12'],
      stableId: 'S1',
      horseId: 'H6',
      remainingWater: 26.0,
      remainingFeed: 7.0,
      scheduleType: 'manual',
    ),
    // Stable 2
    RoomModel(
      roomId: 'R7',
      name: 'Ruangan 7',
      deviceSerial: 'SRIPB1223007',
      status: 'used',
      cctvIds: ['CCTV13', 'CCTV14'],
      stableId: 'S2',
      horseId: 'H7',
      remainingWater: 10.0,
      remainingFeed: 13.0,
      scheduleType: 'penjadwalan',
    ),
    RoomModel(
      roomId: 'R8',
      name: 'Ruangan 8',
      deviceSerial: 'SRIPB1223008',
      status: 'available',
      cctvIds: ['CCTV15', 'CCTV16'],
      stableId: 'S2',
      horseId: 'H8',
      remainingWater: 9.0,
      remainingFeed: 6.5,
      scheduleType: 'otomatis',
    ),
    RoomModel(
      roomId: 'R9',
      name: 'Ruangan 9',
      deviceSerial: 'SRIPB1223009',
      status: 'used',
      cctvIds: ['CCTV17', 'CCTV18'],
      stableId: 'S2',
      horseId: 'H9',
      remainingWater: 31.0,
      remainingFeed: 22.0,
      scheduleType: 'manual',
    ),
    RoomModel(
      roomId: 'R10',
      name: 'Ruangan 10',
      deviceSerial: 'SRIPB1223010',
      status: 'available',
      cctvIds: ['CCTV19', 'CCTV20'],
      stableId: 'S2',
      horseId: 'H10',
      remainingWater: 23.0,
      remainingFeed: 20.0,
      scheduleType: 'penjadwalan',
    ),
    RoomModel(
      roomId: 'R11',
      name: 'Ruangan 11',
      deviceSerial: 'SRIPB1223011',
      status: 'used',
      cctvIds: ['CCTV2', 'CCTV3'],
      stableId: 'S2',
      horseId: 'H11',
      remainingWater: 11.0,
      remainingFeed: 16.0,
      scheduleType: 'otomatis',
    ),
    RoomModel(
      roomId: 'R12',
      name: 'Ruangan 12',
      deviceSerial: 'SRIPB1223012',
      status: 'available',
      cctvIds: ['CCTV4', 'CCTV5'],
      stableId: 'S2',
      horseId: 'H12',
      remainingWater: 41.0,
      remainingFeed: 19.0,
      scheduleType: 'manual',
    ),
    // Stable 3
    RoomModel(
      roomId: 'R13',
      name: 'Ruangan 13',
      deviceSerial: 'SRIPB1223013',
      status: 'used',
      cctvIds: ['CCTV6', 'CCTV7'],
      stableId: 'S3',
      horseId: 'H13',
      remainingWater: 36.0,
      remainingFeed: 3.0,
      scheduleType: 'penjadwalan',
    ),
    RoomModel(
      roomId: 'R14',
      name: 'Ruangan 14',
      deviceSerial: 'SRIPB1223014',
      status: 'available',
      cctvIds: ['CCTV8', 'CCTV9'],
      stableId: 'S3',
      horseId: 'H14',
      remainingWater: 24.0,
      remainingFeed: 10.0,
      scheduleType: 'otomatis',
    ),
    RoomModel(
      roomId: 'R15',
      name: 'Ruangan 15',
      deviceSerial: 'SRIPB1223015',
      status: 'used',
      cctvIds: ['CCTV10', 'CCTV11'],
      stableId: 'S3',
      horseId: 'H15',
      remainingWater: 14.5,
      remainingFeed: 24.0,
      scheduleType: 'manual',
    ),
    RoomModel(
      roomId: 'R16',
      name: 'Ruangan 16',
      deviceSerial: 'SRIPB1223016',
      status: 'available',
      cctvIds: ['CCTV12', 'CCTV13'],
      stableId: 'S3',
      horseId: 'H16',
      remainingWater: 7.0,
      remainingFeed: 16.0,
      scheduleType: 'penjadwalan',
    ),
    RoomModel(
      roomId: 'R17',
      name: 'Ruangan 17',
      deviceSerial: 'SRIPB1223017',
      status: 'used',
      cctvIds: ['CCTV14', 'CCTV15'],
      stableId: 'S3',
      horseId: 'H17',
      remainingWater: 6.0,
      remainingFeed: 2.0,
      scheduleType: 'otomatis',
    ),
    RoomModel(
      roomId: 'R18',
      name: 'Ruangan 18',
      deviceSerial: 'SRIPB1223018',
      status: 'available',
      cctvIds: ['CCTV16', 'CCTV17'],
      stableId: 'S3',
      horseId: 'H18',
      remainingWater: 39.0,
      remainingFeed: 11.0,
      scheduleType: 'manual',
    ),
  ].obs;

  final RxList<CctvModel> cctvList = <CctvModel>[
    CctvModel(
      cctvId: 'CCTV1',
      ipAddress: '172.19.0.193',
      port: 8000,
      username: 'admin',
      password: 'fkh12345',
    ),
    CctvModel(
      cctvId: 'CCTV2',
      ipAddress: '172.19.0.194',
      port: 8001,
      username: 'admin2',
      password: 'fkh12346',
    ),
    CctvModel(
      cctvId: 'CCTV3',
      ipAddress: '172.19.0.195',
      port: 8002,
      username: 'admin3',
      password: 'fkh12347',
    ),
    CctvModel(
      cctvId: 'CCTV4',
      ipAddress: '172.19.0.196',
      port: 8003,
      username: 'admin4',
      password: 'fkh12348',
    ),
    CctvModel(
      cctvId: 'CCTV5',
      ipAddress: '172.19.0.197',
      port: 8004,
      username: 'admin5',
      password: 'fkh12349',
    ),
    CctvModel(
      cctvId: 'CCTV6',
      ipAddress: '172.19.0.198',
      port: 8005,
      username: 'admin6',
      password: 'fkh12350',
    ),
    CctvModel(
      cctvId: 'CCTV7',
      ipAddress: '172.19.0.199',
      port: 8006,
      username: 'admin7',
      password: 'fkh12351',
    ),
    CctvModel(
      cctvId: 'CCTV8',
      ipAddress: '172.19.0.200',
      port: 8007,
      username: 'admin8',
      password: 'fkh12352',
    ),
    CctvModel(
      cctvId: 'CCTV9',
      ipAddress: '172.19.0.201',
      port: 8008,
      username: 'admin9',
      password: 'fkh12353',
    ),
    CctvModel(
      cctvId: 'CCTV10',
      ipAddress: '172.19.0.202',
      port: 8009,
      username: 'admin10',
      password: 'fkh12354',
    ),
    CctvModel(
      cctvId: 'CCTV11',
      ipAddress: '172.19.0.203',
      port: 8010,
      username: 'admin11',
      password: 'fkh12355',
    ),
    CctvModel(
      cctvId: 'CCTV12',
      ipAddress: '172.19.0.204',
      port: 8011,
      username: 'admin12',
      password: 'fkh12356',
    ),
    CctvModel(
      cctvId: 'CCTV13',
      ipAddress: '172.19.0.205',
      port: 8012,
      username: 'admin13',
      password: 'fkh12357',
    ),
    CctvModel(
      cctvId: 'CCTV14',
      ipAddress: '172.19.0.206',
      port: 8013,
      username: 'admin14',
      password: 'fkh12358',
    ),
    CctvModel(
      cctvId: 'CCTV15',
      ipAddress: '172.19.0.207',
      port: 8014,
      username: 'admin15',
      password: 'fkh12359',
    ),
    CctvModel(
      cctvId: 'CCTV16',
      ipAddress: '172.19.0.208',
      port: 8015,
      username: 'admin16',
      password: 'fkh12360',
    ),
    CctvModel(
      cctvId: 'CCTV17',
      ipAddress: '172.19.0.209',
      port: 8016,
      username: 'admin17',
      password: 'fkh12361',
    ),
    CctvModel(
      cctvId: 'CCTV18',
      ipAddress: '172.19.0.210',
      port: 8017,
      username: 'admin18',
      password: 'fkh12362',
    ),
    CctvModel(
      cctvId: 'CCTV19',
      ipAddress: '172.19.0.211',
      port: 8018,
      username: 'admin19',
      password: 'fkh12363',
    ),
    CctvModel(
      cctvId: 'CCTV20',
      ipAddress: '172.19.0.212',
      port: 8019,
      username: 'admin20',
      password: 'fkh12364',
    ),
  ].obs;
  String getCctvNames(List<String> cctvIds) {
    final names = cctvIds.map((id) {
      final cctv = cctvList.firstWhereOrNull((c) => c.cctvId == id);
      if (cctv != null) {
        return '${cctv.ipAddress} (${cctv.cctvId})';
      }
      return id;
    }).toList();
    return names.join(' / ');
  }
}
